CREATE TABLE SALARIES(
    `ID`            INTEGER PRIMARY KEY AUTO_INCREMENT,
    `EMPLOYEE_NAME` VARCHAR(255),
    `SALARY_DATE`   DATE,
    `AMOUNT`        DECIMAL,
    `CURRENCY`      VARCHAR(5));

CREATE TABLE RATES(
    `ID`            INTEGER PRIMARY KEY AUTO_INCREMENT,
    `RATE_DATE`     DATE,
    `RATE_VALUE`    DECIMAL,
    `FROM_CURRENCY` VARCHAR(5),
    `TO_CURRENCY`   VARCHAR(5));